### ISSUE TITLE
Simplify 'Definition' value for 'NMR-ML CV

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#155]
I would suggest the following:
a BFO2.0 anchored controlled terminology providing semantic support to the NMR-ML xml format.
(see website for more information)

if not, proofing and edit (e.g. s/annotrate/annotate/)

**Comment by DSchober** [comment]
I have now put:
"This artefact is an MSI-approved controlled vocabulary primarily developed under COSMOS WP2 governance. The nmrCV is supporting the nmrML XML format with standardized terms. Its primaly role is hence analogous to the mzCV for the PSI-approved mzML XML format."

I don't like to make BFO-usage part of the definition, also as we are fairly agnostic to a TLO and BFO is rather an example of eminence based rather than evidence based good practice. As you know I would use a Bio upper level such as Biotop, in which I can at least trace its consistency.

**Comment by proccaserra** [comment]
I am only stating the fact that NMR_CV uses BFO as tlo (the top level classes are using BFO classes as evidenced by their identifiers). 
I respect your opinion about BFO/Biotop but since the manuscript currently claims compliance with FAIR principles, it seems that indicating reliance one BFO would tick at least the 'reusability' and 'interoperability' boxes, owing to the number of resources in the real of open bio medical ontologies, and be internally consistent.

**Comment by DSchober** [comment]
added BFO mention. Although I feel this is overloading the definition tag.
